name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  oursky/flutter:1.17.1

    steps:
    - uses: actions/checkout@v2
    - run: |
        flutter pub get
        flutter build apk
      working-directory: vignettes/fluid_nav_bar
      
      
